;(function () {
  const locales = window.WhoAiLocales || (window.WhoAiLocales = {})
  locales.en = {
    code: 'en', htmlLang: 'en', title: 'English', nativeName: 'English',
    strings: {
    'meta.title': 'What Animal Are You Today? A Fun Game', 'meta.description': 'A fun game about colourful animals. Type a word and meet your animal for today.',
    'brand.label': 'Who are you today?', 'language.label': 'Language', 'language.menu': 'Choose language', 'skip.content': 'Skip to content', 'themes.label': 'Page style', 'themes.auto': 'auto', 'themes.pastel': 'cosmos', 'themes.neon': 'neon',
    'hero.eyebrow': 'THE SECRET CHARACTER LAB', 'hero.title.one': 'What animal are you', 'hero.title.two': 'today?', 'hero.intro': 'Type your name, nickname, or any word and meet a colourful animal. It will bring you a kind thought for the day.',
    'search.label': 'Who are we looking for?', 'search.help': 'Type a name or any word, then press “find me”.', 'search.placeholder': 'for example, Luna', 'search.submit': 'find me',
    'scan.ready': 'Ready to peek into your animal aura?', 'scan.found': 'Found it!', 'scan.searching': 'looking…', 'scan.searchingOne': 'Matching footprints…', 'scan.searchingTwo': 'Reading your character…', 'scan.searchingThree': 'Catching your colour…', 'scan.frame.1': 'Matching footprints…', 'scan.frame.2': 'Reading your character…', 'scan.frame.3': 'Catching your colour…',
    'stage.label': 'Your animal', 'stage.result': 'Your animal', 'stage.caption': 'Your animal is already collecting bright stories.', 'result.label': 'YOUR INNER ANIMAL', 'result.fallback': 'Your animal', 'result.forecastFallback': 'Today can be a good day.', 'result.tags': 'Animal traits', 'result.signals': 'Animal signals', 'result.forecast': 'What your day may be like', 'result.again': 'another one',
    'tools.label': 'Picture buttons', 'tools.title': 'PICTURE PROMPTS WITH YOUR ANIMAL', 'tools.pastel': 'picture: candy cosmos', 'tools.neon': 'picture: neon safari', 'tools.share.label': 'SAVE OR SHARE YOUR LOOK', 'tools.share': 'share your animal',
    'share.title': 'Who are you today?', 'share.text': 'I am a {identity} 🐾 What are you?', 'feedback.promptCopied': 'Picture text copied.', 'feedback.promptError': 'Could not copy it. Open the site with a secure link.', 'feedback.shareSuccess': 'Done! Send it to a friend so they can meet their animal.', 'feedback.shareCopied': 'Done! The text and link are copied — send them to a friend.', 'feedback.shareError': 'Could not share automatically.', 'feedback.prompt.copied': 'Picture text copied.', 'feedback.prompt.failed': 'Could not copy it. Open the site with a secure link.', 'feedback.share.success': 'Done! Send it to a friend so they can meet their animal.', 'feedback.share.copied': 'Done! The text and link are copied — send them to a friend.', 'feedback.share.failed': 'Could not share automatically.',
    'seo.eyebrow': 'A GAME ABOUT ANIMALS', 'seo.title': 'How do you find your animal?', 'seo.intro': '“Who are you?” is a fun game. Type your name or any word. The game will show you a colourful animal and a kind thought for the day.', 'seo.step.1': 'Type a word.', 'seo.step.2': 'See which animal comes to you.', 'seo.step.3': 'Press a button to make a picture with your animal.',
    'seo.avatar.title': 'Make a picture with your animal', 'seo.avatar.text': 'There are picture buttons below. Press one to make a drawing with your animal.', 'faq.title': 'Questions and answers', 'faq.1.q': 'Is this a game?', 'faq.1.a': 'Yes. It is a fun game about little animals.', 'faq.2.q': 'Why did I get this animal?', 'faq.2.a': 'Your word helps the game choose an animal. Try another word and a different one may come.', 'faq.3.q': 'What are the words about my day?', 'faq.3.a': 'They are a kind thought for today. They cannot tell the future.', 'faq.4.q': 'Can I make a picture?', 'faq.4.a': 'Yes. Press a picture button, then show your animal to friends.',
    },
    dynamic: { fullName: '{adjective} {color} {animal}', shareText: 'I am a {identity} 🐾 What are you?', imagePrompt: 'Create a square 1:1 illustration. The main character is a {animal}, named “{identity}”. Fur colour and main accent: {color} ({hex}); colour the animal in this exact colour with a lively gradient. Background: {scene}. Character: {adjective}. Story: {animalSlogan} {colorSlogan} {adjectiveSlogan} Today’s mood: {forecast} Style: {style}. Animal large in the centre, no writing, logos, or frames.', scene: { forest: 'a fairy-tale forest with tall trees and soft light', water: 'sparkling water, waves, and light splashes', cosmos: 'deep space, star dust, and glowing constellations', mist: 'mysterious mist, gentle hills, and moonlight' }, style: { pastel: 'soft pastel 3D illustration, candy cosmos, round friendly shapes', neon: 'bright neon illustration, safari from the future, crisp graphic lines' } }
  }
})()
