;(function () {
  const locales = window.WhoAiLocales || (window.WhoAiLocales = {})
  locales.es = {
    code: 'es', htmlLang: 'es', title: 'Español', nativeName: 'Español',
    strings: {
    'meta.title': '¿Qué animal eres hoy? Un juego divertido', 'meta.description': 'Un juego divertido de animales de colores. Escribe una palabra y conoce a tu animal de hoy.',
    'brand.label': '¿Quién eres hoy?', 'language.label': 'Idioma', 'language.menu': 'Elegir idioma', 'skip.content': 'Ir al contenido', 'themes.label': 'Estilo de página', 'themes.auto': 'auto', 'themes.pastel': 'cosmos', 'themes.neon': 'neón',
    'hero.eyebrow': 'EL LABORATORIO SECRETO DEL CARÁCTER', 'hero.title.one': '¿Qué animal eres', 'hero.title.two': 'hoy?', 'hero.intro': 'Escribe tu nombre, apodo o cualquier palabra y conoce a un animal de colores. Te traerá una idea amable para el día.',
    'search.label': '¿A quién buscamos?', 'search.help': 'Escribe un nombre o una palabra y pulsa «encuéntrame».', 'search.placeholder': 'por ejemplo, Luna', 'search.submit': 'encuéntrame',
    'scan.ready': '¿Listo para mirar tu aura animal?', 'scan.found': '¡Encontrado!', 'scan.searching': 'buscando…', 'scan.searchingOne': 'Comparamos huellas…', 'scan.searchingTwo': 'Miramos tu carácter…', 'scan.searchingThree': 'Buscamos tu color…', 'scan.frame.1': 'Comparamos huellas…', 'scan.frame.2': 'Miramos tu carácter…', 'scan.frame.3': 'Buscamos tu color…',
    'stage.label': 'Tu animal', 'stage.result': 'Tu animal', 'stage.caption': 'Tu animal ya está reuniendo historias brillantes.', 'result.label': 'TU ANIMAL INTERIOR', 'result.fallback': 'Tu animal', 'result.forecastFallback': 'Hoy puede ser un buen día.', 'result.tags': 'Rasgos del animal', 'result.signals': 'Señales del animal', 'result.forecast': 'Cómo puede ser tu día', 'result.again': 'otro más',
    'tools.label': 'Botones para imágenes', 'tools.title': 'IDEAS DE IMAGEN CON TU ANIMAL', 'tools.pastel': 'imagen: cosmos de caramelo', 'tools.neon': 'imagen: safari neón', 'tools.share.label': 'GUARDA O COMPARTE TU IMAGEN', 'tools.share': 'compartir mi animal',
    'share.title': '¿Quién eres hoy?', 'share.text': 'Soy {identity} 🐾 ¿Y tú?', 'feedback.promptCopied': 'Texto para la imagen copiado.', 'feedback.promptError': 'No se pudo copiar. Abre el sitio con un enlace seguro.', 'feedback.shareSuccess': '¡Listo! Envíalo a un amigo para que conozca a su animal.', 'feedback.shareCopied': '¡Listo! El texto y el enlace están copiados.', 'feedback.shareError': 'No se pudo compartir automáticamente.', 'feedback.prompt.copied': 'Texto para la imagen copiado.', 'feedback.prompt.failed': 'No se pudo copiar. Abre el sitio con un enlace seguro.', 'feedback.share.success': '¡Listo! Envíalo a un amigo para que conozca a su animal.', 'feedback.share.copied': '¡Listo! El texto y el enlace están copiados.', 'feedback.share.failed': 'No se pudo compartir automáticamente.',
    'seo.eyebrow': 'UN JUEGO DE ANIMALES', 'seo.title': '¿Cómo encuentras a tu animal?', 'seo.intro': '«¿Quién eres?» es un juego divertido. Escribe tu nombre o una palabra. El juego te mostrará un animal de colores y una idea amable para el día.', 'seo.step.1': 'Escribe una palabra.', 'seo.step.2': 'Mira qué animal viene a ti.', 'seo.step.3': 'Pulsa un botón para hacer una imagen con tu animal.',
    'seo.avatar.title': 'Haz una imagen con tu animal', 'seo.avatar.text': 'Abajo hay botones de imagen. Pulsa uno para hacer un dibujo con tu animal.', 'faq.title': 'Preguntas y respuestas', 'faq.1.q': '¿Es un juego?', 'faq.1.a': 'Sí. Es un juego divertido sobre animalitos.', 'faq.2.q': '¿Por qué me tocó este animal?', 'faq.2.a': 'Tu palabra ayuda al juego a elegir un animal. Prueba otra palabra y puede venir otro.', 'faq.3.q': '¿Qué son las palabras sobre mi día?', 'faq.3.a': 'Son una idea amable para hoy. No pueden adivinar el futuro.', 'faq.4.q': '¿Puedo hacer una imagen?', 'faq.4.a': 'Sí. Pulsa un botón de imagen y enseña tu animal a tus amigos.',
    },
    dynamic: { fullName: '{adjective} {color} {animal}', shareText: 'Soy {identity} 🐾 ¿Y tú?', imagePrompt: 'Crea una ilustración cuadrada 1:1. El personaje principal es {animal}, llamado «{identity}». Color y detalle principal: {color} ({hex}); pinta al animal con este color y un degradado vivo. Fondo: {scene}. Carácter: {adjective}. Historia: {animalSlogan} {colorSlogan} {adjectiveSlogan} Ánimo de hoy: {forecast} Estilo: {style}. Animal grande en el centro, sin letras, logos ni marcos.', scene: { forest: 'un bosque de cuento con árboles altos y luz suave', water: 'agua brillante, olas y salpicaduras ligeras', cosmos: 'espacio profundo, polvo de estrellas y constelaciones brillantes', mist: 'niebla misteriosa, colinas suaves y luz de luna' }, style: { pastel: 'ilustración 3D pastel suave, cosmos de caramelo y formas redondas amigables', neon: 'ilustración neón brillante, safari del futuro y líneas gráficas claras' } }
  }
})()
