;(function () {
  const locales = window.WhoAiLocales || (window.WhoAiLocales = {})
  locales.it = {
    code: 'it', htmlLang: 'it', title: 'Italiano', nativeName: 'Italiano',
    strings: {
    'meta.title': 'Che animale sei oggi? Un gioco divertente', 'meta.description': 'Un gioco divertente sugli animali colorati. Scrivi una parola e incontra il tuo animale di oggi.',
    'brand.label': 'Chi sei oggi?', 'language.label': 'Lingua', 'language.menu': 'Scegli la lingua', 'skip.content': 'Vai al contenuto', 'themes.label': 'Stile della pagina', 'themes.auto': 'auto', 'themes.pastel': 'cosmo', 'themes.neon': 'neon',
    'hero.eyebrow': 'IL LABORATORIO SEGRETO DEL CARATTERE', 'hero.title.one': 'Che animale sei', 'hero.title.two': 'oggi?', 'hero.intro': 'Scrivi il tuo nome, soprannome o una parola e incontra un animale colorato. Ti porterà un pensiero gentile per la giornata.',
    'search.label': 'Chi cerchiamo?', 'search.help': 'Scrivi un nome o una parola, poi premi «trovami».', 'search.placeholder': 'per esempio, Luna', 'search.submit': 'trovami',
    'scan.ready': 'Pronto a guardare la tua aura animale?', 'scan.found': 'Trovato!', 'scan.searching': 'cerchiamo…', 'scan.searchingOne': 'Confrontiamo le impronte…', 'scan.searchingTwo': 'Guardiamo il tuo carattere…', 'scan.searchingThree': 'Cerchiamo il tuo colore…', 'scan.frame.1': 'Confrontiamo le impronte…', 'scan.frame.2': 'Guardiamo il tuo carattere…', 'scan.frame.3': 'Cerchiamo il tuo colore…',
    'stage.label': 'Il tuo animale', 'stage.result': 'Il tuo animale', 'stage.caption': 'Il tuo animale sta già raccogliendo storie luminose.', 'result.label': 'IL TUO ANIMALE INTERIORE', 'result.fallback': 'Il tuo animale', 'result.forecastFallback': 'Oggi può essere una buona giornata.', 'result.tags': 'Tratti dell’animale', 'result.signals': 'Segnali dell’animale', 'result.forecast': 'Come può essere la tua giornata', 'result.again': 'un altro',
    'tools.label': 'Pulsanti per immagini', 'tools.title': 'IDEE PER IMMAGINI CON IL TUO ANIMALE', 'tools.pastel': 'immagine: cosmo di caramelle', 'tools.neon': 'immagine: safari neon', 'tools.share.label': 'SALVA O CONDIVIDI LA TUA IMMAGINE', 'tools.share': 'condividi il mio animale',
    'share.title': 'Chi sei oggi?', 'share.text': 'Io sono {identity} 🐾 E tu?', 'feedback.promptCopied': 'Testo per l’immagine copiato.', 'feedback.promptError': 'Non è stato possibile copiare. Apri il sito con un link sicuro.', 'feedback.shareSuccess': 'Fatto! Mandalo a un amico così potrà incontrare il suo animale.', 'feedback.shareCopied': 'Fatto! Testo e link sono copiati.', 'feedback.shareError': 'Non è stato possibile condividere automaticamente.', 'feedback.prompt.copied': 'Testo per l’immagine copiato.', 'feedback.prompt.failed': 'Non è stato possibile copiare. Apri il sito con un link sicuro.', 'feedback.share.success': 'Fatto! Mandalo a un amico così potrà incontrare il suo animale.', 'feedback.share.copied': 'Fatto! Testo e link sono copiati.', 'feedback.share.failed': 'Non è stato possibile condividere automaticamente.',
    'seo.eyebrow': 'UN GIOCO SUGLI ANIMALI', 'seo.title': 'Come trovi il tuo animale?', 'seo.intro': '«Chi sei?» è un gioco divertente. Scrivi il tuo nome o una parola. Il gioco ti mostrerà un animale colorato e un pensiero gentile per la giornata.', 'seo.step.1': 'Scrivi una parola.', 'seo.step.2': 'Guarda quale animale viene da te.', 'seo.step.3': 'Premi un pulsante per creare un’immagine con il tuo animale.',
    'seo.avatar.title': 'Crea un’immagine con il tuo animale', 'seo.avatar.text': 'Qui sotto ci sono i pulsanti per le immagini. Premine uno per creare un disegno con il tuo animale.', 'faq.title': 'Domande e risposte', 'faq.1.q': 'È un gioco?', 'faq.1.a': 'Sì. È un gioco divertente sugli animaletti.', 'faq.2.q': 'Perché ho questo animale?', 'faq.2.a': 'La tua parola aiuta il gioco a scegliere un animale. Prova un’altra parola e potrebbe arrivarne un altro.', 'faq.3.q': 'Cosa sono le parole sulla mia giornata?', 'faq.3.a': 'Sono un pensiero gentile per oggi. Non possono indovinare il futuro.', 'faq.4.q': 'Posso creare un’immagine?', 'faq.4.a': 'Sì. Premi un pulsante per immagini e mostra il tuo animale agli amici.',
    },
    dynamic: { fullName: '{adjective} {color} {animal}', shareText: 'Io sono {identity} 🐾 E tu?', imagePrompt: 'Crea un’illustrazione quadrata 1:1. Il personaggio principale è {animal}, chiamato «{identity}». Colore e dettaglio principale: {color} ({hex}); colora l’animale con questo colore e una sfumatura vivace. Sfondo: {scene}. Carattere: {adjective}. Storia: {animalSlogan} {colorSlogan} {adjectiveSlogan} Umore di oggi: {forecast} Stile: {style}. Animale grande al centro, senza scritte, loghi o cornici.', scene: { forest: 'una foresta da fiaba con alberi alti e luce morbida', water: 'acqua scintillante, onde e spruzzi leggeri', cosmos: 'spazio profondo, polvere di stelle e costellazioni luminose', mist: 'nebbia misteriosa, colline dolci e luce lunare' }, style: { pastel: 'illustrazione 3D pastello morbida, cosmo di caramelle e forme tonde amichevoli', neon: 'illustrazione neon vivace, safari del futuro e linee grafiche nette' } }
  }
})()
