;(function () {
  const locales = window.WhoAiLocales || (window.WhoAiLocales = {})
  locales.ko = {
    code: 'ko', htmlLang: 'ko', title: '한국어', nativeName: '한국어',
    strings: {
      'meta.title': '오늘 나는 어떤 동물일까? 재미있는 놀이', 'meta.description': '알록달록 동물을 만나는 재미있는 놀이예요. 단어를 쓰고 오늘의 동물을 만나 보세요.', 'brand.label': '오늘 나는 누구일까?', 'language.label': '언어', 'language.menu': '언어 선택', 'skip.content': '본문으로 이동', 'themes.label': '페이지 스타일', 'themes.auto': '자동', 'themes.pastel': '우주', 'themes.neon': '네온',
      'hero.eyebrow': '비밀 성격 연구소', 'hero.title.one': '오늘 나는 어떤 동물', 'hero.title.two': '일까?', 'hero.intro': '이름, 별명 또는 아무 단어나 써 보세요. 알록달록 동물이 오늘의 따뜻한 말을 전해 줄 거예요.', 'search.label': '누구를 찾을까요?', 'search.help': '이름이나 단어를 쓰고 “나 찾기”를 누르세요.', 'search.placeholder': '예: 루나', 'search.submit': '나 찾기',
      'scan.ready': '동물 기운을 살펴볼 준비가 되었나요?', 'scan.found': '찾았어요!', 'scan.searching': '찾는 중…', 'scan.searchingOne': '발자국을 살펴봐요…', 'scan.searchingTwo': '마음을 살펴봐요…', 'scan.searchingThree': '나만의 색을 찾아요…', 'scan.frame.1': '발자국을 살펴봐요…', 'scan.frame.2': '마음을 살펴봐요…', 'scan.frame.3': '나만의 색을 찾아요…',
      'stage.label': '나의 동물', 'stage.result': '나의 동물', 'stage.caption': '나의 동물이 반짝이는 이야기를 모으고 있어요.', 'result.label': '내 안의 동물', 'result.fallback': '나의 동물', 'result.forecastFallback': '오늘은 좋은 하루가 될 수 있어요.', 'result.tags': '동물의 모습', 'result.signals': '동물의 신호', 'result.forecast': '오늘 하루는 어떨까?', 'result.again': '다른 친구',
      'tools.label': '그림 버튼', 'tools.title': '나의 동물로 그림 만들기', 'tools.pastel': '그림: 사탕 우주', 'tools.neon': '그림: 네온 사파리', 'tools.share.label': '모습을 저장하거나 나눠요', 'tools.share': '내 동물 공유하기', 'share.title': '오늘 나는 누구일까?', 'share.text': '나는 {identity} 🐾 너는 누구야?',
      'feedback.promptCopied': '그림용 글을 복사했어요.', 'feedback.promptError': '복사하지 못했어요. 안전한 링크로 사이트를 열어 보세요.', 'feedback.shareSuccess': '완료! 친구에게 보내서 친구의 동물도 만나게 해 주세요.', 'feedback.shareCopied': '완료! 글과 링크를 복사했어요.', 'feedback.shareError': '자동으로 나누지 못했어요.', 'feedback.prompt.copied': '그림용 글을 복사했어요.', 'feedback.prompt.failed': '복사하지 못했어요. 안전한 링크로 사이트를 열어 보세요.', 'feedback.share.success': '완료! 친구에게 보내서 친구의 동물도 만나게 해 주세요.', 'feedback.share.copied': '완료! 글과 링크를 복사했어요.', 'feedback.share.failed': '자동으로 나누지 못했어요.',
      'seo.eyebrow': '동물 놀이', 'seo.title': '나의 동물을 어떻게 찾을까?', 'seo.intro': '“너는 누구니?”는 재미있는 동물 놀이예요. 이름이나 단어를 쓰면 알록달록 동물과 오늘의 따뜻한 말을 보여 줘요.', 'seo.step.1': '단어를 써요.', 'seo.step.2': '어떤 동물이 왔는지 봐요.', 'seo.step.3': '버튼을 눌러 동물 그림을 만들어요.', 'seo.avatar.title': '나의 동물 그림 만들기', 'seo.avatar.text': '아래 그림 버튼을 누르면 나의 동물 그림을 만들 수 있어요.', 'faq.title': '궁금한 점', 'faq.1.q': '이건 놀이인가요?', 'faq.1.a': '네. 동물 친구를 만나는 재미있는 놀이예요.', 'faq.2.q': '왜 이 동물이 나왔나요?', 'faq.2.a': '쓴 단어가 동물을 고르는 데 도움을 줘요. 다른 단어를 써 보면 다른 친구가 올 수도 있어요.', 'faq.3.q': '오늘에 대한 말은 무엇인가요?', 'faq.3.a': '오늘을 위한 따뜻한 말이에요. 미래를 맞히지는 못해요.', 'faq.4.q': '그림을 만들 수 있나요?', 'faq.4.a': '네. 그림 버튼을 누르고 친구에게 동물을 보여 주세요.'
    },
    dynamic: { fullName: '{adjective} {color} {animal}', shareText: '나는 {identity} 🐾 너는 누구야?', imagePrompt: '정사각형 1:1 그림을 만들어 주세요. 주인공은 {animal}, 이름은 “{identity}”입니다. 주된 색은 {color}({hex})이며 생생한 그라데이션을 사용하세요. 배경: {scene}. 성격: {adjective}. 이야기: {animalSlogan} {colorSlogan} {adjectiveSlogan} 오늘의 기분: {forecast} 스타일: {style}. 동물은 가운데 크게, 글자·로고·테두리는 없이.', scene: { forest: '키 큰 나무와 부드러운 빛이 있는 동화 숲', water: '반짝이는 물, 물결과 가벼운 물보라', cosmos: '깊은 우주, 별가루와 빛나는 별자리', mist: '신비한 안개, 부드러운 언덕과 달빛' }, style: { pastel: '부드러운 파스텔 3D 그림, 사탕 우주와 둥근 친근한 모양', neon: '밝은 네온 그림, 미래의 사파리와 또렷한 선' } }
  }
})()
