;(() => {
  const catalog = window.WhoAiCatalogLocales || (window.WhoAiCatalogLocales = {})
  catalog.it = {
    species: ['volpe','lupo','lince','orso','procione','lontra','castoro','tasso','martora','zibellino','ghiottone','donnola','furetto','visone','puzzola','panda','koala','vombato','canguro','wallaby','quokka','capibara','cincillà','coniglio','lepre','scoiattolo','tamia','marmotta','riccio','pipistrello','bradipo','formichiere','armadillo','tapiro','giraffa','zebra','elefante','rinoceronte','ippopotamo','cammello','lama','alpaca','yak','cervo','alce','bisonte','tigre','leone','ghepardo','leopardo','foca','delfino','orca','beluga','narvalo','balena','squalo','polpo','calamaro','granchio','cavalluccio marino','tartaruga','rana','axolotl','geco','camaleonte','coccodrillo','serpente','gufo','aquila','falco','pappagallo','pinguino','fenicottero','pavone'],
    realms: ['della foresta','della nebbia','delle costellazioni','della spuma marina'],
    baseColors: ['scarlatto','corallo','pesca','ambra','limone','oliva','menta','smeraldo','turchese','azzurro','celeste','zaffiro','indaco','ametista','lilla','lavanda','lampone','rosa','cipria','cioccolato','sabbia','caramello','fumé','grafite','argento','oro','rame','caffè','giada','artico'],
    colorMoods: ['luminoso','scintillante','nella nebbia','al chiaro di luna','succoso','di velluto','del mattino','profondo','al neon','silenzioso'],
    adjectiveRoots: ['scintillante','gentile','coraggioso','sognatore','agile','leggendario','solare','di velluto','svelto','buono','attento','giocherellone','libero','accogliente','vivace','saggio','felice','peloso','audace','calmo','luminoso','veloce','magico','caldo','squillante','brillante','sensibile','allegro','misterioso','straordinario'],
    intensifiers: ['davvero','un poco','specialmente','pazzamente','incredibilmente','in silenzio','molto','con gentilezza','con sincerità','all’infinito'],
    verbs: ['trova','illumina','protegge','accende','raccoglie','trasforma','nota','disegna','abbraccia','inventa','regala','acchiappa','rafforza','apre','crea'],
    themes: ['la gioia','piccole meraviglie','coincidenze luminose','sorrisi','il tuo ritmo','nuove strade','l’ispirazione','pensieri coraggiosi','storie accoglienti','un’aria di festa','scintille','luce morbida','il gioco','l’armonia','avventure fortunate','il tuo carattere','calore','buone notizie','la fantasia','la libertà'],
    forecastMoods: ['Oggi hai un po’ più di coraggio tranquillo.','La giornata comincia con una curiosità leggera.','La tua attenzione arriva proprio al momento giusto.','Dentro di te c’è una riserva di energia calda.','Oggi è facile sentire il tuo ritmo.','Il tuo umore ha voglia di giocare un poco.','Puoi lasciarti essere flessibile.','Nell’aria c’è un entusiasmo silenzioso.','Hai il diritto di scegliere il tuo passo.','Oggi le gioie semplici sono speciali.','La tua bussola interiore punta verso il nuovo.','La giornata invita a decidere con dolcezza.','Dentro di te si sveglia una scintilla creativa.','La calma può essere il tuo superpotere.','Oggi hai voglia di notare le cose belle.','Sei aperto a sorprese piacevoli.','Questa giornata è fatta per un coraggio gentile.','La tua leggerezza fa sorridere gli altri.','Oggi puoi fidarti della prima idea buona.','Hai abbastanza forza per i cambiamenti.','Sei pronto, ma senza essere troppo serio.','Oggi puoi guardare le cose di sempre con occhi nuovi.','È un bel momento per ascoltarti.','La giornata porta un pizzico di ostinazione solare.','Dentro di te c’è spazio per l’ispirazione.','La tua gentilezza si vede anche senza parole.','Oggi hai voglia di muoverti seguendo ciò che ti piace.','Dentro di te c’è una sicurezza calma.','La giornata è pronta per piccole scoperte.','Il tuo umore sa trovare il lato luminoso.'],
    forecastActions: ['Comincia con una piccola cosa che aspetta da tempo.','Fai una pausa breve solo per te.','Di’ sì a un’idea che ti incuriosisce.','Scegli una strada un po’ diversa dal solito.','Regala una parola gentile a qualcuno che ti viene in mente.','Fai il primo passo senza aspettare un piano perfetto.','Metti in ordine un piccolo angolo.','Trova tre cose per cui ringraziare questa giornata.','Fai una cosa di sempre in un modo nuovo.','Lascia posto a una piccola sorpresa.','Fai una domanda che volevi fare da tempo.','Raccogli vicino a te le tue piccole cose preferite.','Dedica un po’ di tempo a ciò che ti fa venire voglia di fare.','Scegli un compito dopo il quale respirerai meglio.','Stacca un momento dal rumore intorno a te.','Nota una cosa bella mentre vai.','Dai alla tua idea almeno dieci minuti di attenzione.','Fai una pausa prima di una risposta importante.','Prova a guardare la situazione da un altro lato.','Lascia perdere il superfluo e tieni il necessario.','Condividi una scoperta che ti ha fatto sorridere.','Permettiti di cambiare idea se è più giusto.','Metti un po’ di movimento o musica nella giornata.','Scegli una chiacchierata che scalda il cuore.','Conserva un momento della giornata in una nota o in una foto.','Fai una cosa utile al tuo ritmo.','Trova un motivo per dirti «grazie».','Comincia dal passo più facile e guarda cosa succede.','Segui la curiosità in una piccola cosa sicura.','Lascia alla fine della giornata un momento per respirare con calma.'],
    forecastFinals: ['Stasera possa restare la sensazione di aver vissuto bene la giornata.','E poi tutto si metta al posto giusto con il tuo ritmo.','Anche un passo piccolo oggi può essere un bel segno.','Conserva questa leggerezza: ti sta benissimo.','Possa esserci spazio per una bella sorpresa.','La cosa importante è non avere fretta con i bei cambiamenti.','Possa la giornata regalarti almeno un sorriso sincero.','Stasera potrai ringraziarti per esserti ascoltato.','La scelta che fai oggi merita cura.','Possa il bello comparire nelle cose più semplici.','E possa esserci un po’ più di calore vicino a te.','Oggi basta essere te stesso: è già tanto.','Possa la fine della giornata essere morbida e accogliente.','Ogni piccola gioia di oggi conta.','Tieni la rotta verso ciò che è importante per te.','Possa la giornata lasciarti una storia bella.','Non devi fare tutto per sentire che stai andando avanti.','Possa arrivare la parola giusta al momento giusto.','La tua attenzione può rendere speciale questa giornata.','Possa esserci più di un motivo per sorridere senza motivo.','Lascia un po’ di posto a una bella coincidenza.','Possa la giornata ricordarti che ci riesci a modo tuo.','Il calore che doni può tornare quando meno te l’aspetti.','Possa la sera portarti una dolce sensazione di conclusione.','Oggi non serve cercare la perfezione: basta notare ciò che è vivo.','Possa tu trovare persone e pensieri che ti sostengono.','Lascia che accada qualcosa di bello senza aspettarti troppo.','Possa questa giornata darti fiducia per domani.','La cosa più preziosa oggi è restare in contatto con te stesso.','Possa la sera incontrarti con calma e un piccolo orgoglio.'],
    templates: {
      animalName: '{species} {realm}', colorName: '{mood} {base}', adjectiveName: '{intensifier} {root}',
      animalSlogan: 'Il tuo animale «{name}» {verb} {theme}.', colorSlogan: 'Il tuo colore «{name}» {verb} {theme}.', adjectiveSlogan: 'La tua forza «{name}» {verb} {theme}.',
      forecast: '{mood} {action} {final}', fullName: '{adjective} {color} {animal}',
    },
  }
})()
